#!/bin/bash
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 10000 --num_points 50 --model_name mine_gender_data_weak_feedback_seed_0_lambda_10000_n_50
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 10000 --num_points 100 --model_name mine_gender_data_weak_feedback_seed_0_lambda_10000_n_100
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 10000 --num_points 250 --model_name mine_gender_data_weak_feedback_seed_0_lambda_10000_n_250

# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 200 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_200
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 300 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_400
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 500 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_500

# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 50 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_50
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 100 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_100
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 250 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_250


# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 50000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_0_lambda_50000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 1 --mine true --eta 100000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_1_lambda_100000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 1 --mine true --eta 50000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_1_lambda_50000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 2 --mine true --eta 100000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_2_lambda_100000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 2 --mine true --eta 50000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_2_lambda_50000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 3 --mine true --eta 100000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_3_lambda_100000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 3 --mine true --eta 50000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_3_lambda_50000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 4 --mine true --eta 100000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_4_lambda_100000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 4 --mine true --eta 50000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_4_lambda_50000_n_10

# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 10000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_0_lambda_10000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 0 --mine true --eta 5000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_0_lambda_5000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 1 --mine true --eta 10000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_1_lambda_10000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 1 --mine true --eta 5000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_1_lambda_5000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 2 --mine true --eta 10000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_2_lambda_10000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 2 --mine true --eta 5000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_2_lambda_5000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 3 --mine true --eta 10000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_3_lambda_10000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 3 --mine true --eta 5000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_3_lambda_5000_n_10
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 4 --mine true --eta 10000 --num_points 5 --model_name mine_gender_data_weak_feedback_seed_4_lambda_10000_n_5
# python main.py --train-batch 20 --test-batch 10 --n_epoch 50 --data_dir gender_data --trainWithMap --fw_sample 50  --random_seed 4 --mine true --eta 5000 --num_points 10 --model_name mine_gender_data_weak_feedback_seed_4_lambda_5000_n_10